import { notFound } from "next/navigation";
import Link from "next/link";
import { Card, Note, SectionHeading } from "@/components/ui";
import { getGrant, getInquiry, getTrial, listQuestions } from "@/lib/repo";
import { getActiveParticipant } from "@/lib/session";
import { decideAction } from "@/app/actions";

export const dynamic = "force-dynamic";

const STATE_COPY: Record<string, { title: string; body: string }> = {
  draft: { title: "Still a draft", body: "Nothing has been shared yet." },
  shared: {
    title: "Shared, waiting to be picked up",
    body: "The site has it. Nobody has read it yet. Sites answer on their own schedule, and there is nothing further you need to do right now.",
  },
  acknowledged: {
    title: "Someone at the site has it",
    body: "A coordinator has opened your inquiry. This is not enrolment and does not mean you have been accepted or screened.",
  },
  needs_information: {
    title: "The site has asked for something",
    body: "There is a note below explaining what would help.",
  },
  answered: {
    title: "You have a reply",
    body: "A person at the site reviewed and sent this. Read it below.",
  },
  closed: {
    title: "Closed",
    body: "This inquiry is closed. You can start a new one at any time, and nothing you saved has been lost.",
  },
};

/** The participant's view of one inquiry: who owns it, what state it is in. */
export default async function InquiryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const inquiry = getInquiry(id);
  const participant = await getActiveParticipant();

  // Authorization: an inquiry is readable only by the person who created it.
  if (!inquiry || inquiry.participantId !== participant.id) notFound();

  const trial = getTrial(inquiry.trialId);
  const grant = inquiry.grantId ? getGrant(inquiry.grantId) : null;
  const questions = listQuestions({ inquiryId: inquiry.id });
  const copy = STATE_COPY[inquiry.state] ?? STATE_COPY.shared;
  const answered = questions.filter((question) => question.answer);

  return (
    <div className="space-y-5">
      <Link href="/passport" className="inline-flex min-h-11 items-center text-sm text-teal hover:underline">← My passport</Link>

      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-ink">{copy.title}</h1>
        <p className="mt-1 text-sm leading-relaxed text-ink-soft">{copy.body}</p>
      </div>

      <Card className="space-y-2 p-4">
        <p className="text-sm font-medium text-ink">{trial?.briefTitle ?? inquiry.trialId}</p>
        <p className="text-xs text-ink-faint">
          Shared with {grant?.recipientLabel ?? "the study team"} on{" "}
          {new Date(inquiry.createdAt).toLocaleDateString()}
        </p>
        <p className="text-xs text-ink-faint">
          Fields shared: {grant?.allowedFields.join(", ") || "none"}
          {grant?.state === "revoked" ? " · you have revoked this access" : ""}
        </p>
      </Card>

      {inquiry.coordinatorNote ? (
        <Card className="p-4">
          <SectionHeading>Note from the site</SectionHeading>
          <p className="text-sm leading-relaxed text-ink-soft">{inquiry.coordinatorNote}</p>
        </Card>
      ) : null}

      {answered.length ? (
        <section>
          <SectionHeading hint="Written and reviewed by a person at the site, not generated by this app.">
            Answers
          </SectionHeading>
          <ul className="space-y-2.5">
            {answered.map((question) => (
              <li key={question.id}>
                <Card className="p-4">
                  <p className="text-sm font-medium text-ink">{question.text}</p>
                  <p className="mt-2 text-sm leading-relaxed text-ink-soft">{question.answer}</p>
                  <p className="mt-2 border-t border-rule pt-2 text-[11px] text-ink-faint">
                    {question.answeredBy}
                    {question.answerCitation ? ` · ${question.answerCitation}` : ""}
                    {question.answeredAt ? ` · ${new Date(question.answeredAt).toLocaleString()}` : ""}
                  </p>
                </Card>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {questions.filter((question) => !question.answer).length ? (
        <section>
          <SectionHeading>Still open</SectionHeading>
          <Card className="p-4">
            <ul className="space-y-1.5">
              {questions.filter((question) => !question.answer).map((question) => (
                <li key={question.id} className="text-sm text-ink-soft">
                  · {question.text}{" "}
                  <span className="text-xs text-ink-faint">({question.state.replace(/_/g, " ")})</span>
                </li>
              ))}
            </ul>
          </Card>
        </section>
      ) : null}

      <section>
        <SectionHeading hint="Whatever you choose, you keep everything you have saved here.">
          Where you stand
        </SectionHeading>
        <Card className="space-y-2 p-4">
          {[
            { value: "participating", label: "I have agreed to take part", hint: "Adds the study's visits to your calendar." },
            { value: "considering", label: "I need more time", hint: "Keeps this open with no follow-up from us." },
            { value: "declined", label: "I am not interested", hint: "Closes the inquiry. Nothing is lost and nobody will chase you." },
          ].map((option) => (
            <form key={option.value} action={decideAction}>
              <input type="hidden" name="trialId" value={inquiry.trialId} />
              <input type="hidden" name="inquiryId" value={inquiry.id} />
              <input type="hidden" name="decision" value={option.value} />
              <button
                type="submit"
                className="flex min-h-11 w-full items-center justify-between gap-3 rounded-lg border border-rule px-3.5 py-2.5 text-left hover:border-teal hover:bg-teal-soft"
              >
                <span>
                  <span className="block text-sm font-medium text-ink">{option.label}</span>
                  <span className="block text-xs text-ink-soft">{option.hint}</span>
                </span>
                <span aria-hidden className="text-teal">→</span>
              </button>
            </form>
          ))}
        </Card>
      </section>

      <Note>
        Leaving Trial Passport is not the same as withdrawing from a study. If you are already
        taking part in research, contact that study&rsquo;s team directly — deleting anything here
        does not change your participation or your medical records.
      </Note>
    </div>
  );
}
