import { notFound } from "next/navigation";
import { CaretRight } from "@phosphor-icons/react/dist/ssr";
import { PrintButton } from "@/components/CountedTextarea";
import { Callout, Card, Pill, ScreenHeader, SectionHeading } from "@/components/ui";
import { getGrant, getInquiry, getTrial, listQuestions, markInquirySeen } from "@/lib/repo";
import { getActiveParticipant } from "@/lib/session";
import { decideAction, questionFollowUpAction } from "@/app/actions";
import { isAnswered, QUESTION_STATE_LABEL } from "@/lib/questions";

export const dynamic = "force-dynamic";

const STATE_COPY: Record<string, { title: string; body: string }> = {
  shared: { title: "Shared, waiting to be picked up", body: "The team has it and nobody has read it yet. Sites answer on their own schedule. There is nothing you need to do." },
  acknowledged: { title: "Someone on the team has it", body: "A coordinator has opened your inquiry. This is not enrolment, and it does not mean you have been accepted or screened." },
  needs_information: { title: "The team has asked for something", body: "Their note below explains what would help." },
  answered: { title: "You have a reply", body: "A person on the team reviewed and sent this." },
  closed: { title: "Closed", body: "You can start a new inquiry at any time. Nothing you saved has been lost." },
};

/** One conversation with a study team: who owns it, and what state it is in. */
export default async function InquiryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const inquiry = getInquiry(id);
  const participant = await getActiveParticipant();
  // Authorization: only the person who created an inquiry can read it.
  if (!inquiry || inquiry.participantId !== participant.id) notFound();

  markInquirySeen(inquiry.id);

  const trial = getTrial(inquiry.trialId);
  const grant = inquiry.grantId ? getGrant(inquiry.grantId) : null;
  const questions = listQuestions({ inquiryId: inquiry.id });
  const copy = STATE_COPY[inquiry.state] ?? STATE_COPY.shared;
  const answered = questions.filter((q) => isAnswered(q));
  const open = questions.filter((q) => !isAnswered(q));

  const choices = [
    { value: "participating", label: "I have agreed to take part", hint: "Adds the study's confirmed visits to your timeline." },
    { value: "considering", label: "I need more time", hint: "Keeps this open. Nobody will chase you." },
    { value: "help", label: "Please help me contact the study team", hint: "Sends that request to the coordinator." },
    { value: "declined", label: "I am not interested", hint: "Closes this. Nothing is lost." },
  ];

  return (
    <div className="space-y-4">
      <ScreenHeader back="/inbox" title={copy.title} sub={copy.body} action={<PrintButton />} />

      <Card className="p-4">
        <p className="text-[14px] font-bold leading-snug text-ink">{trial?.briefTitle ?? inquiry.trialId}</p>
        <p className="mt-1 text-[12px] text-ink-soft">
          Shared with {grant?.recipientLabel ?? "the study team"} on {new Date(inquiry.createdAt).toLocaleDateString()}
        </p>
        <p className="mt-1 flex flex-wrap items-center gap-1.5 text-[12px] text-ink-faint">
          Shared: {grant?.allowedFields.join(", ") || "nothing"}
          {grant?.state === "revoked" ? <Pill tone="blush">Access revoked</Pill> : null}
        </p>
      </Card>

      {inquiry.coordinatorNote ? (
        <Callout tone="caution" title="Note from the team">{inquiry.coordinatorNote}</Callout>
      ) : null}

      {answered.length ? (
        <section>
          <SectionHeading hint="Written and reviewed by a person on the team, not generated by this app.">Answers</SectionHeading>
          <ul className="space-y-2.5">
            {answered.map((question) => (
              <Card as="li" key={question.id} className="p-4">
                <p className="text-[13.5px] font-bold text-ink">{question.text}</p>
                <p className="mt-2 rounded-[14px] bg-mint-soft p-3 text-[13px] leading-relaxed text-ink">{question.answer}</p>
                <p className="mt-2 text-[11px] leading-relaxed text-ink-faint">
                  {question.answeredBy}{question.answerCitation ? `. ${question.answerCitation}` : ""}
                </p>
                {question.state === "resolved" ? (
                  <p className="mt-2"><Pill tone="mint">You marked this resolved</Pill></p>
                ) : (
                  <form action={questionFollowUpAction} className="no-print mt-2.5 flex gap-2">
                    <input type="hidden" name="questionId" value={question.id} />
                    <button type="submit" name="intent" value="resolve" className="press min-h-11 flex-1 rounded-full border border-rule-strong bg-surface text-[12.5px] font-bold text-ink hover:bg-sunken">This answers it</button>
                    <button type="submit" name="intent" value="reopen" className="press min-h-11 flex-1 rounded-full border border-rule-strong bg-surface text-[12.5px] font-bold text-ink hover:bg-sunken">I still have a question</button>
                  </form>
                )}
              </Card>
            ))}
          </ul>
        </section>
      ) : null}

      {open.length ? (
        <section>
          <SectionHeading>Still open</SectionHeading>
          <Card className="px-4">
            <ul>
              {open.map((question) => (
                <li key={question.id} className="flex items-center justify-between gap-3 border-b border-rule py-3 last:border-0">
                  <span className="text-[13px] text-ink">{question.text}</span>
                  <Pill>{question.answer ? "Reopened" : question.state === "draft_answer" ? "Being answered" : QUESTION_STATE_LABEL[question.state]}</Pill>
                </li>
              ))}
            </ul>
          </Card>
        </section>
      ) : null}

      <details className="rounded-[16px] border border-rule bg-surface px-4">
        <summary className="flex min-h-12 cursor-pointer items-center text-[13px] font-bold text-iris">What you sent</summary>
        <pre className="mb-4 whitespace-pre-wrap font-mono text-[11.5px] leading-relaxed text-ink-soft">{inquiry.message}</pre>
      </details>

      <section className="no-print">
        <SectionHeading hint="Whatever you choose, you keep everything you have saved.">Where you stand</SectionHeading>
        <Card className="overflow-hidden">
          {choices.map((choice) => (
            <form key={choice.value} action={decideAction} className="border-b border-rule last:border-0">
              <input type="hidden" name="trialId" value={inquiry.trialId} />
              <input type="hidden" name="inquiryId" value={inquiry.id} />
              <input type="hidden" name="decision" value={choice.value} />
              <button type="submit" className="press flex min-h-16 w-full items-center gap-3 px-4 py-3 text-left hover:bg-sunken">
                <span className="min-w-0 flex-1">
                  <span className="block text-[14px] font-bold text-ink">{choice.label}</span>
                  <span className="block text-[12.5px] text-ink-soft">{choice.hint}</span>
                </span>
                <CaretRight size={16} weight="bold" className="text-iris" />
              </button>
            </form>
          ))}
        </Card>
      </section>

      <Callout tone="neutral">
        Leaving Mozaic is not the same as withdrawing from a study. If you are taking part
        in research, contact that study&rsquo;s team directly. Deleting anything here does not change
        your participation or your medical records.
      </Callout>
    </div>
  );
}
